# Uncomment the next line to define a global platform for your project


target 'ZXScrollNavigationBar' do
    platform :ios, '8.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for ZXScrollNavigationBar
  
    pod 'Masonry'
    pod 'ZXScrollNavigationBar'
    
end
